################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
D:/work/WIFI_GD32VW/Github_GD32VW55x/MSDK/app/atcmd.c \
D:/work/WIFI_GD32VW/Github_GD32VW55x/MSDK/ble/app/ble_init.c \
D:/work/WIFI_GD32VW/Github_GD32VW55x/MSDK/app/cmd_shell.c \
D:/work/WIFI_GD32VW/Github_GD32VW55x/MSDK/app/iperf.c \
D:/work/WIFI_GD32VW/Github_GD32VW55x/MSDK/app/iperf3_main.c \
D:/work/WIFI_GD32VW/Github_GD32VW55x/MSDK/app/main.c \
D:/work/WIFI_GD32VW/Github_GD32VW55x/MSDK/app/mqtt_app/mqtt_cmd.c \
D:/work/WIFI_GD32VW/Github_GD32VW55x/MSDK/app/ota_demo.c \
D:/work/WIFI_GD32VW/Github_GD32VW55x/MSDK/app/ping.c 

C_DEPS += \
./app/atcmd.d \
./app/ble_init.d \
./app/cmd_shell.d \
./app/iperf.d \
./app/iperf3_main.d \
./app/main.d \
./app/mqtt_cmd.d \
./app/ota_demo.d \
./app/ping.d 

OBJS += \
./app/atcmd.o \
./app/ble_init.o \
./app/cmd_shell.o \
./app/iperf.o \
./app/iperf3_main.o \
./app/main.o \
./app/mqtt_cmd.o \
./app/ota_demo.o \
./app/ping.o 


# Each subdirectory must supply rules for building sources it contributes
app/atcmd.o: D:/work/WIFI_GD32VW/Github_GD32VW55x/MSDK/app/atcmd.c app/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable  -g -std=c99 -DCFG_RTOS -DPLATFORM_OS_FREERTOS -I"..\..\..\..\lwip\iperf3" -I"..\..\..\..\lwip\iperf" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\lib" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\src\reg" -I"..\..\..\..\plf\src\raw_flash" -I"..\..\..\..\plf\src\qspi_flash" -I"..\..\..\..\plf\src\dma" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\src\uart" -I"..\..\..\..\plf\src\spi" -I"..\..\..\..\plf\src\spi_i2s" -I"..\..\..\..\plf\src\nvds" -I"..\..\..\..\plf\src\rf" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\plf\riscv\NMSIS\DSP\Include" -I"..\..\..\..\plf\riscv\NMSIS\DSP\Include\dsp" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\rtos\FreeRTOS\Source\include" -I"..\..\..\..\rtos\FreeRTOS\Source\portable\riscv32" -I"..\..\..\..\rtos\FreeRTOS\config" -I"..\..\..\..\lwip\lwip-2.2.0\src\include" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.2.0\port" -I"..\..\..\..\lwip\libcoap\include" -I"..\..\..\..\lwip\libcoap\port" -I"..\..\..\..\FatFS\port" -I"..\..\..\..\FatFS\src" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\include" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\library" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\tests\include\spe" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\..\ROM-EXPORT\halcomm" -I"..\..\..\..\..\ROM-EXPORT\symbol" -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\app\mqtt_app" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\wifi_manager\wpas" -I"..\..\..\..\blesw\src\export" -I"..\..\..\..\ble\app" -I"..\..\..\..\ble\profile" -I"..\..\..\..\ble\profile\datatrans" -I"..\..\..\..\ble\profile\dis" -I"..\..\..\..\ble\profile\sample" -I"..\..\..\..\ble\profile\throughput" -I"..\..\..\..\ble\profile\bas" -I"..\..\..\..\ble\profile\ota" -I"..\..\..\..\util\include" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

app/ble_init.o: D:/work/WIFI_GD32VW/Github_GD32VW55x/MSDK/ble/app/ble_init.c app/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable  -g -std=c99 -DCFG_RTOS -DPLATFORM_OS_FREERTOS -I"..\..\..\..\lwip\iperf3" -I"..\..\..\..\lwip\iperf" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\lib" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\src\reg" -I"..\..\..\..\plf\src\raw_flash" -I"..\..\..\..\plf\src\qspi_flash" -I"..\..\..\..\plf\src\dma" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\src\uart" -I"..\..\..\..\plf\src\spi" -I"..\..\..\..\plf\src\spi_i2s" -I"..\..\..\..\plf\src\nvds" -I"..\..\..\..\plf\src\rf" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\plf\riscv\NMSIS\DSP\Include" -I"..\..\..\..\plf\riscv\NMSIS\DSP\Include\dsp" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\rtos\FreeRTOS\Source\include" -I"..\..\..\..\rtos\FreeRTOS\Source\portable\riscv32" -I"..\..\..\..\rtos\FreeRTOS\config" -I"..\..\..\..\lwip\lwip-2.2.0\src\include" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.2.0\port" -I"..\..\..\..\lwip\libcoap\include" -I"..\..\..\..\lwip\libcoap\port" -I"..\..\..\..\FatFS\port" -I"..\..\..\..\FatFS\src" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\include" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\library" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\tests\include\spe" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\..\ROM-EXPORT\halcomm" -I"..\..\..\..\..\ROM-EXPORT\symbol" -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\app\mqtt_app" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\wifi_manager\wpas" -I"..\..\..\..\blesw\src\export" -I"..\..\..\..\ble\app" -I"..\..\..\..\ble\profile" -I"..\..\..\..\ble\profile\datatrans" -I"..\..\..\..\ble\profile\dis" -I"..\..\..\..\ble\profile\sample" -I"..\..\..\..\ble\profile\throughput" -I"..\..\..\..\ble\profile\bas" -I"..\..\..\..\ble\profile\ota" -I"..\..\..\..\util\include" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

app/cmd_shell.o: D:/work/WIFI_GD32VW/Github_GD32VW55x/MSDK/app/cmd_shell.c app/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable  -g -std=c99 -DCFG_RTOS -DPLATFORM_OS_FREERTOS -I"..\..\..\..\lwip\iperf3" -I"..\..\..\..\lwip\iperf" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\lib" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\src\reg" -I"..\..\..\..\plf\src\raw_flash" -I"..\..\..\..\plf\src\qspi_flash" -I"..\..\..\..\plf\src\dma" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\src\uart" -I"..\..\..\..\plf\src\spi" -I"..\..\..\..\plf\src\spi_i2s" -I"..\..\..\..\plf\src\nvds" -I"..\..\..\..\plf\src\rf" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\plf\riscv\NMSIS\DSP\Include" -I"..\..\..\..\plf\riscv\NMSIS\DSP\Include\dsp" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\rtos\FreeRTOS\Source\include" -I"..\..\..\..\rtos\FreeRTOS\Source\portable\riscv32" -I"..\..\..\..\rtos\FreeRTOS\config" -I"..\..\..\..\lwip\lwip-2.2.0\src\include" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.2.0\port" -I"..\..\..\..\lwip\libcoap\include" -I"..\..\..\..\lwip\libcoap\port" -I"..\..\..\..\FatFS\port" -I"..\..\..\..\FatFS\src" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\include" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\library" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\tests\include\spe" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\..\ROM-EXPORT\halcomm" -I"..\..\..\..\..\ROM-EXPORT\symbol" -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\app\mqtt_app" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\wifi_manager\wpas" -I"..\..\..\..\blesw\src\export" -I"..\..\..\..\ble\app" -I"..\..\..\..\ble\profile" -I"..\..\..\..\ble\profile\datatrans" -I"..\..\..\..\ble\profile\dis" -I"..\..\..\..\ble\profile\sample" -I"..\..\..\..\ble\profile\throughput" -I"..\..\..\..\ble\profile\bas" -I"..\..\..\..\ble\profile\ota" -I"..\..\..\..\util\include" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

app/iperf.o: D:/work/WIFI_GD32VW/Github_GD32VW55x/MSDK/app/iperf.c app/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable  -g -std=c99 -DCFG_RTOS -DPLATFORM_OS_FREERTOS -I"..\..\..\..\lwip\iperf3" -I"..\..\..\..\lwip\iperf" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\lib" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\src\reg" -I"..\..\..\..\plf\src\raw_flash" -I"..\..\..\..\plf\src\qspi_flash" -I"..\..\..\..\plf\src\dma" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\src\uart" -I"..\..\..\..\plf\src\spi" -I"..\..\..\..\plf\src\spi_i2s" -I"..\..\..\..\plf\src\nvds" -I"..\..\..\..\plf\src\rf" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\plf\riscv\NMSIS\DSP\Include" -I"..\..\..\..\plf\riscv\NMSIS\DSP\Include\dsp" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\rtos\FreeRTOS\Source\include" -I"..\..\..\..\rtos\FreeRTOS\Source\portable\riscv32" -I"..\..\..\..\rtos\FreeRTOS\config" -I"..\..\..\..\lwip\lwip-2.2.0\src\include" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.2.0\port" -I"..\..\..\..\lwip\libcoap\include" -I"..\..\..\..\lwip\libcoap\port" -I"..\..\..\..\FatFS\port" -I"..\..\..\..\FatFS\src" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\include" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\library" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\tests\include\spe" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\..\ROM-EXPORT\halcomm" -I"..\..\..\..\..\ROM-EXPORT\symbol" -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\app\mqtt_app" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\wifi_manager\wpas" -I"..\..\..\..\blesw\src\export" -I"..\..\..\..\ble\app" -I"..\..\..\..\ble\profile" -I"..\..\..\..\ble\profile\datatrans" -I"..\..\..\..\ble\profile\dis" -I"..\..\..\..\ble\profile\sample" -I"..\..\..\..\ble\profile\throughput" -I"..\..\..\..\ble\profile\bas" -I"..\..\..\..\ble\profile\ota" -I"..\..\..\..\util\include" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

app/iperf3_main.o: D:/work/WIFI_GD32VW/Github_GD32VW55x/MSDK/app/iperf3_main.c app/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable  -g -std=c99 -DCFG_RTOS -DPLATFORM_OS_FREERTOS -I"..\..\..\..\lwip\iperf3" -I"..\..\..\..\lwip\iperf" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\lib" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\src\reg" -I"..\..\..\..\plf\src\raw_flash" -I"..\..\..\..\plf\src\qspi_flash" -I"..\..\..\..\plf\src\dma" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\src\uart" -I"..\..\..\..\plf\src\spi" -I"..\..\..\..\plf\src\spi_i2s" -I"..\..\..\..\plf\src\nvds" -I"..\..\..\..\plf\src\rf" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\plf\riscv\NMSIS\DSP\Include" -I"..\..\..\..\plf\riscv\NMSIS\DSP\Include\dsp" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\rtos\FreeRTOS\Source\include" -I"..\..\..\..\rtos\FreeRTOS\Source\portable\riscv32" -I"..\..\..\..\rtos\FreeRTOS\config" -I"..\..\..\..\lwip\lwip-2.2.0\src\include" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.2.0\port" -I"..\..\..\..\lwip\libcoap\include" -I"..\..\..\..\lwip\libcoap\port" -I"..\..\..\..\FatFS\port" -I"..\..\..\..\FatFS\src" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\include" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\library" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\tests\include\spe" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\..\ROM-EXPORT\halcomm" -I"..\..\..\..\..\ROM-EXPORT\symbol" -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\app\mqtt_app" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\wifi_manager\wpas" -I"..\..\..\..\blesw\src\export" -I"..\..\..\..\ble\app" -I"..\..\..\..\ble\profile" -I"..\..\..\..\ble\profile\datatrans" -I"..\..\..\..\ble\profile\dis" -I"..\..\..\..\ble\profile\sample" -I"..\..\..\..\ble\profile\throughput" -I"..\..\..\..\ble\profile\bas" -I"..\..\..\..\ble\profile\ota" -I"..\..\..\..\util\include" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

app/main.o: D:/work/WIFI_GD32VW/Github_GD32VW55x/MSDK/app/main.c app/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable  -g -std=c99 -DCFG_RTOS -DPLATFORM_OS_FREERTOS -I"..\..\..\..\lwip\iperf3" -I"..\..\..\..\lwip\iperf" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\lib" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\src\reg" -I"..\..\..\..\plf\src\raw_flash" -I"..\..\..\..\plf\src\qspi_flash" -I"..\..\..\..\plf\src\dma" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\src\uart" -I"..\..\..\..\plf\src\spi" -I"..\..\..\..\plf\src\spi_i2s" -I"..\..\..\..\plf\src\nvds" -I"..\..\..\..\plf\src\rf" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\plf\riscv\NMSIS\DSP\Include" -I"..\..\..\..\plf\riscv\NMSIS\DSP\Include\dsp" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\rtos\FreeRTOS\Source\include" -I"..\..\..\..\rtos\FreeRTOS\Source\portable\riscv32" -I"..\..\..\..\rtos\FreeRTOS\config" -I"..\..\..\..\lwip\lwip-2.2.0\src\include" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.2.0\port" -I"..\..\..\..\lwip\libcoap\include" -I"..\..\..\..\lwip\libcoap\port" -I"..\..\..\..\FatFS\port" -I"..\..\..\..\FatFS\src" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\include" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\library" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\tests\include\spe" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\..\ROM-EXPORT\halcomm" -I"..\..\..\..\..\ROM-EXPORT\symbol" -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\app\mqtt_app" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\wifi_manager\wpas" -I"..\..\..\..\blesw\src\export" -I"..\..\..\..\ble\app" -I"..\..\..\..\ble\profile" -I"..\..\..\..\ble\profile\datatrans" -I"..\..\..\..\ble\profile\dis" -I"..\..\..\..\ble\profile\sample" -I"..\..\..\..\ble\profile\throughput" -I"..\..\..\..\ble\profile\bas" -I"..\..\..\..\ble\profile\ota" -I"..\..\..\..\util\include" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

app/mqtt_cmd.o: D:/work/WIFI_GD32VW/Github_GD32VW55x/MSDK/app/mqtt_app/mqtt_cmd.c app/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable  -g -std=c99 -DCFG_RTOS -DPLATFORM_OS_FREERTOS -I"..\..\..\..\lwip\iperf3" -I"..\..\..\..\lwip\iperf" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\lib" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\src\reg" -I"..\..\..\..\plf\src\raw_flash" -I"..\..\..\..\plf\src\qspi_flash" -I"..\..\..\..\plf\src\dma" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\src\uart" -I"..\..\..\..\plf\src\spi" -I"..\..\..\..\plf\src\spi_i2s" -I"..\..\..\..\plf\src\nvds" -I"..\..\..\..\plf\src\rf" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\plf\riscv\NMSIS\DSP\Include" -I"..\..\..\..\plf\riscv\NMSIS\DSP\Include\dsp" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\rtos\FreeRTOS\Source\include" -I"..\..\..\..\rtos\FreeRTOS\Source\portable\riscv32" -I"..\..\..\..\rtos\FreeRTOS\config" -I"..\..\..\..\lwip\lwip-2.2.0\src\include" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.2.0\port" -I"..\..\..\..\lwip\libcoap\include" -I"..\..\..\..\lwip\libcoap\port" -I"..\..\..\..\FatFS\port" -I"..\..\..\..\FatFS\src" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\include" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\library" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\tests\include\spe" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\..\ROM-EXPORT\halcomm" -I"..\..\..\..\..\ROM-EXPORT\symbol" -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\app\mqtt_app" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\wifi_manager\wpas" -I"..\..\..\..\blesw\src\export" -I"..\..\..\..\ble\app" -I"..\..\..\..\ble\profile" -I"..\..\..\..\ble\profile\datatrans" -I"..\..\..\..\ble\profile\dis" -I"..\..\..\..\ble\profile\sample" -I"..\..\..\..\ble\profile\throughput" -I"..\..\..\..\ble\profile\bas" -I"..\..\..\..\ble\profile\ota" -I"..\..\..\..\util\include" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

app/ota_demo.o: D:/work/WIFI_GD32VW/Github_GD32VW55x/MSDK/app/ota_demo.c app/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable  -g -std=c99 -DCFG_RTOS -DPLATFORM_OS_FREERTOS -I"..\..\..\..\lwip\iperf3" -I"..\..\..\..\lwip\iperf" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\lib" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\src\reg" -I"..\..\..\..\plf\src\raw_flash" -I"..\..\..\..\plf\src\qspi_flash" -I"..\..\..\..\plf\src\dma" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\src\uart" -I"..\..\..\..\plf\src\spi" -I"..\..\..\..\plf\src\spi_i2s" -I"..\..\..\..\plf\src\nvds" -I"..\..\..\..\plf\src\rf" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\plf\riscv\NMSIS\DSP\Include" -I"..\..\..\..\plf\riscv\NMSIS\DSP\Include\dsp" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\rtos\FreeRTOS\Source\include" -I"..\..\..\..\rtos\FreeRTOS\Source\portable\riscv32" -I"..\..\..\..\rtos\FreeRTOS\config" -I"..\..\..\..\lwip\lwip-2.2.0\src\include" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.2.0\port" -I"..\..\..\..\lwip\libcoap\include" -I"..\..\..\..\lwip\libcoap\port" -I"..\..\..\..\FatFS\port" -I"..\..\..\..\FatFS\src" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\include" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\library" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\tests\include\spe" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\..\ROM-EXPORT\halcomm" -I"..\..\..\..\..\ROM-EXPORT\symbol" -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\app\mqtt_app" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\wifi_manager\wpas" -I"..\..\..\..\blesw\src\export" -I"..\..\..\..\ble\app" -I"..\..\..\..\ble\profile" -I"..\..\..\..\ble\profile\datatrans" -I"..\..\..\..\ble\profile\dis" -I"..\..\..\..\ble\profile\sample" -I"..\..\..\..\ble\profile\throughput" -I"..\..\..\..\ble\profile\bas" -I"..\..\..\..\ble\profile\ota" -I"..\..\..\..\util\include" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

app/ping.o: D:/work/WIFI_GD32VW/Github_GD32VW55x/MSDK/app/ping.c app/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable  -g -std=c99 -DCFG_RTOS -DPLATFORM_OS_FREERTOS -I"..\..\..\..\lwip\iperf3" -I"..\..\..\..\lwip\iperf" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\lib" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\src\reg" -I"..\..\..\..\plf\src\raw_flash" -I"..\..\..\..\plf\src\qspi_flash" -I"..\..\..\..\plf\src\dma" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\src\uart" -I"..\..\..\..\plf\src\spi" -I"..\..\..\..\plf\src\spi_i2s" -I"..\..\..\..\plf\src\nvds" -I"..\..\..\..\plf\src\rf" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\plf\riscv\NMSIS\DSP\Include" -I"..\..\..\..\plf\riscv\NMSIS\DSP\Include\dsp" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\rtos\FreeRTOS\Source\include" -I"..\..\..\..\rtos\FreeRTOS\Source\portable\riscv32" -I"..\..\..\..\rtos\FreeRTOS\config" -I"..\..\..\..\lwip\lwip-2.2.0\src\include" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.2.0\port" -I"..\..\..\..\lwip\libcoap\include" -I"..\..\..\..\lwip\libcoap\port" -I"..\..\..\..\FatFS\port" -I"..\..\..\..\FatFS\src" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\include" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\library" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\tests\include\spe" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\..\ROM-EXPORT\halcomm" -I"..\..\..\..\..\ROM-EXPORT\symbol" -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\app\mqtt_app" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\wifi_manager\wpas" -I"..\..\..\..\blesw\src\export" -I"..\..\..\..\ble\app" -I"..\..\..\..\ble\profile" -I"..\..\..\..\ble\profile\datatrans" -I"..\..\..\..\ble\profile\dis" -I"..\..\..\..\ble\profile\sample" -I"..\..\..\..\ble\profile\throughput" -I"..\..\..\..\ble\profile\bas" -I"..\..\..\..\ble\profile\ota" -I"..\..\..\..\util\include" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


clean: clean-app

clean-app:
	-$(RM) ./app/atcmd.d ./app/atcmd.o ./app/ble_init.d ./app/ble_init.o ./app/cmd_shell.d ./app/cmd_shell.o ./app/iperf.d ./app/iperf.o ./app/iperf3_main.d ./app/iperf3_main.o ./app/main.d ./app/main.o ./app/mqtt_cmd.d ./app/mqtt_cmd.o ./app/ota_demo.d ./app/ota_demo.o ./app/ping.d ./app/ping.o

.PHONY: clean-app

