################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
D:/work/WIFI_GD32VW/Github_GD32VW55x/MSDK/wifi_manager/wifi_eloop.c \
D:/work/WIFI_GD32VW/Github_GD32VW55x/MSDK/wifi_manager/wifi_init.c \
D:/work/WIFI_GD32VW/Github_GD32VW55x/MSDK/wifi_manager/wifi_management.c \
D:/work/WIFI_GD32VW/Github_GD32VW55x/MSDK/wifi_manager/wifi_net_ip.c \
D:/work/WIFI_GD32VW/Github_GD32VW55x/MSDK/wifi_manager/wifi_netlink.c \
D:/work/WIFI_GD32VW/Github_GD32VW55x/MSDK/wifi_manager/wifi_softap_provisioning.c \
D:/work/WIFI_GD32VW/Github_GD32VW55x/MSDK/wifi_manager/wifi_vif.c \
D:/work/WIFI_GD32VW/Github_GD32VW55x/MSDK/wifi_manager/wifi_wpa.c 

C_DEPS += \
./wifi_manager/wifi_eloop.d \
./wifi_manager/wifi_init.d \
./wifi_manager/wifi_management.d \
./wifi_manager/wifi_net_ip.d \
./wifi_manager/wifi_netlink.d \
./wifi_manager/wifi_softap_provisioning.d \
./wifi_manager/wifi_vif.d \
./wifi_manager/wifi_wpa.d 

OBJS += \
./wifi_manager/wifi_eloop.o \
./wifi_manager/wifi_init.o \
./wifi_manager/wifi_management.o \
./wifi_manager/wifi_net_ip.o \
./wifi_manager/wifi_netlink.o \
./wifi_manager/wifi_softap_provisioning.o \
./wifi_manager/wifi_vif.o \
./wifi_manager/wifi_wpa.o 


# Each subdirectory must supply rules for building sources it contributes
wifi_manager/wifi_eloop.o: D:/work/WIFI_GD32VW/Github_GD32VW55x/MSDK/wifi_manager/wifi_eloop.c wifi_manager/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable  -g -std=c99 -DCFG_RTOS -DPLATFORM_OS_FREERTOS -I"..\..\..\..\lwip\iperf3" -I"..\..\..\..\lwip\iperf" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\lib" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\src\reg" -I"..\..\..\..\plf\src\raw_flash" -I"..\..\..\..\plf\src\qspi_flash" -I"..\..\..\..\plf\src\dma" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\src\uart" -I"..\..\..\..\plf\src\spi" -I"..\..\..\..\plf\src\spi_i2s" -I"..\..\..\..\plf\src\nvds" -I"..\..\..\..\plf\src\rf" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\plf\riscv\NMSIS\DSP\Include" -I"..\..\..\..\plf\riscv\NMSIS\DSP\Include\dsp" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\rtos\FreeRTOS\Source\include" -I"..\..\..\..\rtos\FreeRTOS\Source\portable\riscv32" -I"..\..\..\..\rtos\FreeRTOS\config" -I"..\..\..\..\lwip\lwip-2.2.0\src\include" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.2.0\port" -I"..\..\..\..\lwip\libcoap\include" -I"..\..\..\..\lwip\libcoap\port" -I"..\..\..\..\FatFS\port" -I"..\..\..\..\FatFS\src" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\include" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\library" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\tests\include\spe" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\..\ROM-EXPORT\halcomm" -I"..\..\..\..\..\ROM-EXPORT\symbol" -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\app\mqtt_app" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\wifi_manager\wpas" -I"..\..\..\..\blesw\src\export" -I"..\..\..\..\ble\app" -I"..\..\..\..\ble\profile" -I"..\..\..\..\ble\profile\datatrans" -I"..\..\..\..\ble\profile\dis" -I"..\..\..\..\ble\profile\sample" -I"..\..\..\..\ble\profile\throughput" -I"..\..\..\..\ble\profile\bas" -I"..\..\..\..\ble\profile\ota" -I"..\..\..\..\util\include" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wifi_manager/wifi_init.o: D:/work/WIFI_GD32VW/Github_GD32VW55x/MSDK/wifi_manager/wifi_init.c wifi_manager/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable  -g -std=c99 -DCFG_RTOS -DPLATFORM_OS_FREERTOS -I"..\..\..\..\lwip\iperf3" -I"..\..\..\..\lwip\iperf" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\lib" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\src\reg" -I"..\..\..\..\plf\src\raw_flash" -I"..\..\..\..\plf\src\qspi_flash" -I"..\..\..\..\plf\src\dma" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\src\uart" -I"..\..\..\..\plf\src\spi" -I"..\..\..\..\plf\src\spi_i2s" -I"..\..\..\..\plf\src\nvds" -I"..\..\..\..\plf\src\rf" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\plf\riscv\NMSIS\DSP\Include" -I"..\..\..\..\plf\riscv\NMSIS\DSP\Include\dsp" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\rtos\FreeRTOS\Source\include" -I"..\..\..\..\rtos\FreeRTOS\Source\portable\riscv32" -I"..\..\..\..\rtos\FreeRTOS\config" -I"..\..\..\..\lwip\lwip-2.2.0\src\include" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.2.0\port" -I"..\..\..\..\lwip\libcoap\include" -I"..\..\..\..\lwip\libcoap\port" -I"..\..\..\..\FatFS\port" -I"..\..\..\..\FatFS\src" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\include" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\library" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\tests\include\spe" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\..\ROM-EXPORT\halcomm" -I"..\..\..\..\..\ROM-EXPORT\symbol" -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\app\mqtt_app" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\wifi_manager\wpas" -I"..\..\..\..\blesw\src\export" -I"..\..\..\..\ble\app" -I"..\..\..\..\ble\profile" -I"..\..\..\..\ble\profile\datatrans" -I"..\..\..\..\ble\profile\dis" -I"..\..\..\..\ble\profile\sample" -I"..\..\..\..\ble\profile\throughput" -I"..\..\..\..\ble\profile\bas" -I"..\..\..\..\ble\profile\ota" -I"..\..\..\..\util\include" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wifi_manager/wifi_management.o: D:/work/WIFI_GD32VW/Github_GD32VW55x/MSDK/wifi_manager/wifi_management.c wifi_manager/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable  -g -std=c99 -DCFG_RTOS -DPLATFORM_OS_FREERTOS -I"..\..\..\..\lwip\iperf3" -I"..\..\..\..\lwip\iperf" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\lib" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\src\reg" -I"..\..\..\..\plf\src\raw_flash" -I"..\..\..\..\plf\src\qspi_flash" -I"..\..\..\..\plf\src\dma" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\src\uart" -I"..\..\..\..\plf\src\spi" -I"..\..\..\..\plf\src\spi_i2s" -I"..\..\..\..\plf\src\nvds" -I"..\..\..\..\plf\src\rf" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\plf\riscv\NMSIS\DSP\Include" -I"..\..\..\..\plf\riscv\NMSIS\DSP\Include\dsp" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\rtos\FreeRTOS\Source\include" -I"..\..\..\..\rtos\FreeRTOS\Source\portable\riscv32" -I"..\..\..\..\rtos\FreeRTOS\config" -I"..\..\..\..\lwip\lwip-2.2.0\src\include" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.2.0\port" -I"..\..\..\..\lwip\libcoap\include" -I"..\..\..\..\lwip\libcoap\port" -I"..\..\..\..\FatFS\port" -I"..\..\..\..\FatFS\src" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\include" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\library" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\tests\include\spe" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\..\ROM-EXPORT\halcomm" -I"..\..\..\..\..\ROM-EXPORT\symbol" -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\app\mqtt_app" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\wifi_manager\wpas" -I"..\..\..\..\blesw\src\export" -I"..\..\..\..\ble\app" -I"..\..\..\..\ble\profile" -I"..\..\..\..\ble\profile\datatrans" -I"..\..\..\..\ble\profile\dis" -I"..\..\..\..\ble\profile\sample" -I"..\..\..\..\ble\profile\throughput" -I"..\..\..\..\ble\profile\bas" -I"..\..\..\..\ble\profile\ota" -I"..\..\..\..\util\include" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wifi_manager/wifi_net_ip.o: D:/work/WIFI_GD32VW/Github_GD32VW55x/MSDK/wifi_manager/wifi_net_ip.c wifi_manager/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable  -g -std=c99 -DCFG_RTOS -DPLATFORM_OS_FREERTOS -I"..\..\..\..\lwip\iperf3" -I"..\..\..\..\lwip\iperf" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\lib" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\src\reg" -I"..\..\..\..\plf\src\raw_flash" -I"..\..\..\..\plf\src\qspi_flash" -I"..\..\..\..\plf\src\dma" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\src\uart" -I"..\..\..\..\plf\src\spi" -I"..\..\..\..\plf\src\spi_i2s" -I"..\..\..\..\plf\src\nvds" -I"..\..\..\..\plf\src\rf" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\plf\riscv\NMSIS\DSP\Include" -I"..\..\..\..\plf\riscv\NMSIS\DSP\Include\dsp" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\rtos\FreeRTOS\Source\include" -I"..\..\..\..\rtos\FreeRTOS\Source\portable\riscv32" -I"..\..\..\..\rtos\FreeRTOS\config" -I"..\..\..\..\lwip\lwip-2.2.0\src\include" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.2.0\port" -I"..\..\..\..\lwip\libcoap\include" -I"..\..\..\..\lwip\libcoap\port" -I"..\..\..\..\FatFS\port" -I"..\..\..\..\FatFS\src" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\include" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\library" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\tests\include\spe" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\..\ROM-EXPORT\halcomm" -I"..\..\..\..\..\ROM-EXPORT\symbol" -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\app\mqtt_app" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\wifi_manager\wpas" -I"..\..\..\..\blesw\src\export" -I"..\..\..\..\ble\app" -I"..\..\..\..\ble\profile" -I"..\..\..\..\ble\profile\datatrans" -I"..\..\..\..\ble\profile\dis" -I"..\..\..\..\ble\profile\sample" -I"..\..\..\..\ble\profile\throughput" -I"..\..\..\..\ble\profile\bas" -I"..\..\..\..\ble\profile\ota" -I"..\..\..\..\util\include" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wifi_manager/wifi_netlink.o: D:/work/WIFI_GD32VW/Github_GD32VW55x/MSDK/wifi_manager/wifi_netlink.c wifi_manager/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable  -g -std=c99 -DCFG_RTOS -DPLATFORM_OS_FREERTOS -I"..\..\..\..\lwip\iperf3" -I"..\..\..\..\lwip\iperf" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\lib" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\src\reg" -I"..\..\..\..\plf\src\raw_flash" -I"..\..\..\..\plf\src\qspi_flash" -I"..\..\..\..\plf\src\dma" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\src\uart" -I"..\..\..\..\plf\src\spi" -I"..\..\..\..\plf\src\spi_i2s" -I"..\..\..\..\plf\src\nvds" -I"..\..\..\..\plf\src\rf" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\plf\riscv\NMSIS\DSP\Include" -I"..\..\..\..\plf\riscv\NMSIS\DSP\Include\dsp" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\rtos\FreeRTOS\Source\include" -I"..\..\..\..\rtos\FreeRTOS\Source\portable\riscv32" -I"..\..\..\..\rtos\FreeRTOS\config" -I"..\..\..\..\lwip\lwip-2.2.0\src\include" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.2.0\port" -I"..\..\..\..\lwip\libcoap\include" -I"..\..\..\..\lwip\libcoap\port" -I"..\..\..\..\FatFS\port" -I"..\..\..\..\FatFS\src" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\include" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\library" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\tests\include\spe" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\..\ROM-EXPORT\halcomm" -I"..\..\..\..\..\ROM-EXPORT\symbol" -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\app\mqtt_app" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\wifi_manager\wpas" -I"..\..\..\..\blesw\src\export" -I"..\..\..\..\ble\app" -I"..\..\..\..\ble\profile" -I"..\..\..\..\ble\profile\datatrans" -I"..\..\..\..\ble\profile\dis" -I"..\..\..\..\ble\profile\sample" -I"..\..\..\..\ble\profile\throughput" -I"..\..\..\..\ble\profile\bas" -I"..\..\..\..\ble\profile\ota" -I"..\..\..\..\util\include" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wifi_manager/wifi_softap_provisioning.o: D:/work/WIFI_GD32VW/Github_GD32VW55x/MSDK/wifi_manager/wifi_softap_provisioning.c wifi_manager/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable  -g -std=c99 -DCFG_RTOS -DPLATFORM_OS_FREERTOS -I"..\..\..\..\lwip\iperf3" -I"..\..\..\..\lwip\iperf" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\lib" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\src\reg" -I"..\..\..\..\plf\src\raw_flash" -I"..\..\..\..\plf\src\qspi_flash" -I"..\..\..\..\plf\src\dma" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\src\uart" -I"..\..\..\..\plf\src\spi" -I"..\..\..\..\plf\src\spi_i2s" -I"..\..\..\..\plf\src\nvds" -I"..\..\..\..\plf\src\rf" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\plf\riscv\NMSIS\DSP\Include" -I"..\..\..\..\plf\riscv\NMSIS\DSP\Include\dsp" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\rtos\FreeRTOS\Source\include" -I"..\..\..\..\rtos\FreeRTOS\Source\portable\riscv32" -I"..\..\..\..\rtos\FreeRTOS\config" -I"..\..\..\..\lwip\lwip-2.2.0\src\include" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.2.0\port" -I"..\..\..\..\lwip\libcoap\include" -I"..\..\..\..\lwip\libcoap\port" -I"..\..\..\..\FatFS\port" -I"..\..\..\..\FatFS\src" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\include" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\library" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\tests\include\spe" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\..\ROM-EXPORT\halcomm" -I"..\..\..\..\..\ROM-EXPORT\symbol" -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\app\mqtt_app" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\wifi_manager\wpas" -I"..\..\..\..\blesw\src\export" -I"..\..\..\..\ble\app" -I"..\..\..\..\ble\profile" -I"..\..\..\..\ble\profile\datatrans" -I"..\..\..\..\ble\profile\dis" -I"..\..\..\..\ble\profile\sample" -I"..\..\..\..\ble\profile\throughput" -I"..\..\..\..\ble\profile\bas" -I"..\..\..\..\ble\profile\ota" -I"..\..\..\..\util\include" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wifi_manager/wifi_vif.o: D:/work/WIFI_GD32VW/Github_GD32VW55x/MSDK/wifi_manager/wifi_vif.c wifi_manager/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable  -g -std=c99 -DCFG_RTOS -DPLATFORM_OS_FREERTOS -I"..\..\..\..\lwip\iperf3" -I"..\..\..\..\lwip\iperf" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\lib" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\src\reg" -I"..\..\..\..\plf\src\raw_flash" -I"..\..\..\..\plf\src\qspi_flash" -I"..\..\..\..\plf\src\dma" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\src\uart" -I"..\..\..\..\plf\src\spi" -I"..\..\..\..\plf\src\spi_i2s" -I"..\..\..\..\plf\src\nvds" -I"..\..\..\..\plf\src\rf" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\plf\riscv\NMSIS\DSP\Include" -I"..\..\..\..\plf\riscv\NMSIS\DSP\Include\dsp" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\rtos\FreeRTOS\Source\include" -I"..\..\..\..\rtos\FreeRTOS\Source\portable\riscv32" -I"..\..\..\..\rtos\FreeRTOS\config" -I"..\..\..\..\lwip\lwip-2.2.0\src\include" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.2.0\port" -I"..\..\..\..\lwip\libcoap\include" -I"..\..\..\..\lwip\libcoap\port" -I"..\..\..\..\FatFS\port" -I"..\..\..\..\FatFS\src" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\include" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\library" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\tests\include\spe" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\..\ROM-EXPORT\halcomm" -I"..\..\..\..\..\ROM-EXPORT\symbol" -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\app\mqtt_app" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\wifi_manager\wpas" -I"..\..\..\..\blesw\src\export" -I"..\..\..\..\ble\app" -I"..\..\..\..\ble\profile" -I"..\..\..\..\ble\profile\datatrans" -I"..\..\..\..\ble\profile\dis" -I"..\..\..\..\ble\profile\sample" -I"..\..\..\..\ble\profile\throughput" -I"..\..\..\..\ble\profile\bas" -I"..\..\..\..\ble\profile\ota" -I"..\..\..\..\util\include" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

wifi_manager/wifi_wpa.o: D:/work/WIFI_GD32VW/Github_GD32VW55x/MSDK/wifi_manager/wifi_wpa.c wifi_manager/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GD RISC-V MCU C Compiler'
	riscv-nuclei-elf-gcc -march=rv32imafcbp -mcmodel=medlow -msmall-data-limit=8 -msave-restore -mabi=ilp32f -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -fno-unroll-loops -Werror -Wunused -Wuninitialized -Wall -Wno-format -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable  -g -std=c99 -DCFG_RTOS -DPLATFORM_OS_FREERTOS -I"..\..\..\..\lwip\iperf3" -I"..\..\..\..\lwip\iperf" -I"..\..\..\..\macsw\export" -I"..\..\..\..\macsw\import" -I"..\..\..\..\plf\riscv\arch" -I"..\..\..\..\plf\riscv\arch\boot" -I"..\..\..\..\plf\riscv\arch\lib" -I"..\..\..\..\plf\riscv\arch\ll" -I"..\..\..\..\plf\riscv\arch\compiler" -I"..\..\..\..\plf\src" -I"..\..\..\..\plf\src\reg" -I"..\..\..\..\plf\src\raw_flash" -I"..\..\..\..\plf\src\qspi_flash" -I"..\..\..\..\plf\src\dma" -I"..\..\..\..\plf\src\time" -I"..\..\..\..\plf\src\trng" -I"..\..\..\..\plf\src\uart" -I"..\..\..\..\plf\src\spi" -I"..\..\..\..\plf\src\spi_i2s" -I"..\..\..\..\plf\src\nvds" -I"..\..\..\..\plf\src\rf" -I"..\..\..\..\plf\riscv\gd32vw55x" -I"..\..\..\..\plf\riscv\NMSIS\Core\Include" -I"..\..\..\..\plf\riscv\NMSIS\DSP\Include" -I"..\..\..\..\plf\riscv\NMSIS\DSP\Include\dsp" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral" -I"..\..\..\..\plf\GD32VW55x_standard_peripheral\Include" -I"..\..\..\..\rtos\rtos_wrapper" -I"..\..\..\..\rtos\FreeRTOS\Source\include" -I"..\..\..\..\rtos\FreeRTOS\Source\portable\riscv32" -I"..\..\..\..\rtos\FreeRTOS\config" -I"..\..\..\..\lwip\lwip-2.2.0\src\include" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\compat\posix" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\lwip" -I"..\..\..\..\lwip\lwip-2.2.0\src\include\lwip\apps" -I"..\..\..\..\lwip\lwip-2.2.0\port" -I"..\..\..\..\lwip\libcoap\include" -I"..\..\..\..\lwip\libcoap\port" -I"..\..\..\..\FatFS\port" -I"..\..\..\..\FatFS\src" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\include" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\library" -I"..\..\..\..\mbedtls\mbedtls-3.6.2\tests\include\spe" -I"..\..\..\..\..\ROM-EXPORT\bootloader" -I"..\..\..\..\..\ROM-EXPORT\halcomm" -I"..\..\..\..\..\ROM-EXPORT\symbol" -I"..\..\..\..\..\config" -I"..\..\..\..\app" -I"..\..\..\..\app\mqtt_app" -I"..\..\..\..\wifi_manager" -I"..\..\..\..\wifi_manager\wpas" -I"..\..\..\..\blesw\src\export" -I"..\..\..\..\ble\app" -I"..\..\..\..\ble\profile" -I"..\..\..\..\ble\profile\datatrans" -I"..\..\..\..\ble\profile\dis" -I"..\..\..\..\ble\profile\sample" -I"..\..\..\..\ble\profile\throughput" -I"..\..\..\..\ble\profile\bas" -I"..\..\..\..\ble\profile\ota" -I"..\..\..\..\util\include" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -Wa,-adhlns=$@.lst   -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


clean: clean-wifi_manager

clean-wifi_manager:
	-$(RM) ./wifi_manager/wifi_eloop.d ./wifi_manager/wifi_eloop.o ./wifi_manager/wifi_init.d ./wifi_manager/wifi_init.o ./wifi_manager/wifi_management.d ./wifi_manager/wifi_management.o ./wifi_manager/wifi_net_ip.d ./wifi_manager/wifi_net_ip.o ./wifi_manager/wifi_netlink.d ./wifi_manager/wifi_netlink.o ./wifi_manager/wifi_softap_provisioning.d ./wifi_manager/wifi_softap_provisioning.o ./wifi_manager/wifi_vif.d ./wifi_manager/wifi_vif.o ./wifi_manager/wifi_wpa.d ./wifi_manager/wifi_wpa.o

.PHONY: clean-wifi_manager

